use mydatabase;
select * from mytable limit 5;
select * from mytable;
ALTER TABLE mytable
ADD COLUMN purchase_frequency_days INT;
UPDATE mytable
SET purchase_frequency_days = CASE frequency_of_purchases
    WHEN 'Weekly' THEN 7
    WHEN 'Fortnightly' THEN 14
    WHEN 'Bi-Weekly' THEN 14
    WHEN 'Monthly' THEN 30
    WHEN 'Quarterly' THEN 90
    WHEN 'Every 3 months' THEN 90
    WHEN 'Annually' THEN 365
    ELSE NULL
END;

show columns from mytable; 
ALTER TABLE mytable 
ADD COLUMN age_group VARCHAR(50);
UPDATE mytable
SET age_group = CASE 
    WHEN age <= 30 THEN 'Young Adult'
    WHEN age > 30 AND age <= 45 THEN 'Adult'
    WHEN age > 45 AND age <= 60 THEN 'Middle-aged'
    ELSE 'Senior'
END;

ALTER TABLE mytable
RENAME COLUMN age_agroup TO age_group;


ALTER TABLE mytable
RENAME COLUMN `Customer ID` TO customer_id;

ALTER TABLE mytable
RENAME COLUMN `Age` TO age;

ALTER TABLE mytable
RENAME COLUMN `Gender` TO gender;

ALTER TABLE mytable
RENAME COLUMN `Item Purchased` TO item_purchased;

ALTER TABLE mytable
RENAME COLUMN `Category` TO category;

ALTER TABLE mytable
RENAME COLUMN `Purchase Amount (USD)` TO purchase_amount;

ALTER TABLE mytable
RENAME COLUMN `Location` TO location;

ALTER TABLE mytable
RENAME COLUMN `Size` TO size;

ALTER TABLE mytable
RENAME COLUMN `Color` TO color;

ALTER TABLE mytable
RENAME COLUMN `Season` TO season;

ALTER TABLE mytable
RENAME COLUMN `Review Rating` TO review_rating;

ALTER TABLE mytable
RENAME COLUMN `Subscription Status` TO subscription_status;

ALTER TABLE mytable
RENAME COLUMN `Shipping Type` TO shipping_type;

ALTER TABLE mytable
RENAME COLUMN `Discount Applied` TO discount_applied;

ALTER TABLE mytable
RENAME COLUMN `Promo Code Used` TO promo_code_used;

ALTER TABLE mytable
RENAME COLUMN `Previous Purchases` TO previous_purchases;

ALTER TABLE mytable
RENAME COLUMN `Payment Method` TO payment_method;

ALTER TABLE mytable
RENAME COLUMN `Frequency of Purchases` TO frequency_of_purchases;

select * from mytable;

#1. what is the total revenue generated by male vs. female customers?
SELECT gender,
       SUM(purchase_amount) AS revenue
FROM mytable
GROUP BY gender;

#2. which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from mytable
where discount_applied ='Yes' and purchase_amount >= (select AVG(purchase_amount) from mytable);

#3. which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as "Average Purchase Rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

#4. Compare the average Purchase Amounts Between the Standard and Express Shipping.
 select shipping_type,round(avg(purchase_amount),2) as round
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type;

#5. Do Subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id)as total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2) as total_revenue 
from mytable
group by subscription_status
order by total_revenue ,avg_spend desc; 

#6. Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
(round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*) * 100,2)) as discount_rate
from mytable 
group by item_purchased 
order by discount_rate desc
limit 5;

#7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases and show the count of each segment .
 with customer_type as (
 select customer_id, previous_purchases,
 case
	when previous_purchases = 1 then 'New' 
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from mytable 
 )
 select customer_segment ,count(*) as "Number of Customers"
 from customer_type 
 group by customer_segment;
 
#8. What are the top 3 most purchased products within each category? 
with item_counts as (
	select category ,
	item_purchased,
	count(customer_id) as total_orders,
	ROW_NUMBER() over (partition by category order by count(customer_id) desc)  as item_rank
from mytable
group by category ,item_purchased
)
select item_rank,
category ,
item_purchased ,
total_orders
from item_counts
where item_rank <=3;

#9. Are Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id)as repeat_buyer
from mytable 
where previous_purchases > 5
group by subscription_status;

#10. What are the revenue contribution of each age group ?
select age_group,
SUM(purchase_amount)as total_revenue
from mytable
group by age_group
order by total_revenue desc;
